package com.pei.service;

/**
 * Provides a styled HTML wrapper for Markdown content displayed in WebView.
 */
public class MarkdownTemplate {
    private static final String BASE_CSS = String.join("\n",
            "html, body {",
            "  margin: 0; padding: 0;",
            "  font-family: 'Segoe UI', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji', Arial, sans-serif;",
            "  font-size: 14px;",
            "  line-height: 1.7;",
            "  color: #1f2937;",
            "}",
            "body {",
            "  padding: 2px;",
            "}",
            "* {",
            "  box-sizing: border-box;",
            "}",
            "h1, h2, h3, h4, h5, h6 {",
            "  margin: 0.6em 0 0.4em;",
            "  font-weight: 600;",
            "}",
            "p { margin: 0.5em 0; }",
            "ul, ol { margin: 0.4em 0 0.4em 1.2em; }",
            "li { margin: 0.2em 0; }",
            "img {",
            "  max-width: 100%;",
            "  height: auto;",
            "  display: block;",
            "}",
            "code {",
            "  background: #f3f4f6;",
            "  border-radius: 4px;",
            "  padding: 0 4px;",
            "  font-family: Consolas, 'Courier New', monospace;",
            "  word-break: break-word;",
            "}",
            "pre {",
            "  background: #f3f4f6;",
            "  border-radius: 6px;",
            "  padding: 10px;",
            "  overflow-x: auto;",
            "  white-space: pre-wrap;",
            "  word-wrap: break-word;",
            "}",
            "pre code {",
            "  background: transparent;",
            "  padding: 0;",
            "}",
            "blockquote {",
            "  margin: 0.6em 0;",
            "  padding: 0.4em 0.8em;",
            "  border-left: 4px solid #d1d5db;",
            "  color: #4b5563;",
            "  background: #f9fafb;",
            "  border-radius: 6px;",
            "}",
            "table {",
            "  border-collapse: collapse;",
            "  width: 100%;",
            "}",
            "th, td {",
            "  border: 1px solid #e5e7eb;",
            "  padding: 6px 8px;",
            "}",
            "a { color: #2563eb; text-decoration: none; }",
            "a:hover { text-decoration: underline; }",
            "/* dark theme support */",
            "@media (prefers-color-scheme: dark) {",
            "  html, body { color: #e5e7eb; background: transparent; }",
            "  code { background: #111827; }",
            "  pre { background: #111827; }",
            "  blockquote { background: #0b1220; border-left-color: #374151; color: #cbd5e1; }",
            "  th, td { border-color: #374151; }",
            "  a { color: #93c5fd; }",
            "}",
            "/* emoji rendering tweaks */",
            "span.emoji, .emoji {",
            "  font-family: 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji', 'Apple Color Emoji', 'Segoe UI', Arial, sans-serif;",
            "}"
    );

    public static String wrap(String bodyHtml) {
        String safe = bodyHtml == null ? "" : bodyHtml;
        return "<html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><style>" + BASE_CSS + "</style></head><body>" + safe + "</body></html>";
    }
}
